# Generated by Django 3.2.16 on 2025-01-15 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserQuery',
        ),
    ]
